# config.yml
backend:
  name: github
  repo: raulghiurau/reformedliving # Path to your GitHub repository

# # This line should *not* be indented
publish_mode: editorial_workflow

media_folder: "img/assets"
public-folder: "uploads"

collections:
  - name: 'blog'
    label: 'RL Posts'
    folder: '_posts/blogs/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
      - { lable: 'Author', name: 'author', widget: 'string' }
      - { lable: 'Author-title', name: 'author-title', widget: 'string' }
      - { lable: 'Author-image', name: 'author-image', widget: 'image', required: false }
      - { lable: 'Duration', name: 'duration', widget: 'string' }
      - { lable: 'Category', name: 'category', widget: 'select', options: ['finance', 'faith', 'family', 'entertainment', 'technology', 'daily walk'], default: 'faith' }
      - { lable: 'Tags', name: 'tags', widget: 'string', required: false }
      - { lable: 'Image', name: 'image', widget: 'image', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }

  - name: 'resources'
    label: 'RL Resources'
    folder: '_posts/resources/'
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    editor:
      preview: false
    fields:
      - { label: 'Layout', name: 'layout', widget: 'hidden', default: 'post' }
      - { label: 'Title', name: 'title', widget: 'string' }
      - { label: 'Publish Date', name: 'date', widget: 'datetime' }
      - { label: 'Excerpt', name: 'excerpt', widget: 'string' }
      - { lable: 'Author', name: 'author', widget: 'string' }
      - { lable: 'Duration', name: 'duration', widget: 'string' }
      - { lable: 'Category', name: 'category', widget: 'string' }
      - { lable: 'Tags', name: 'tags', widget: 'string', required: false }
      - { lable: 'Image', name: 'image', widget: 'image', required: false }
      - { label: 'Body', name: 'body', widget: 'markdown' }
